backend:
  name: git-gateway
  branch: master

# Borrar despues de desarrollo
local_backend: true
# Borrar despues de desarrollo

media_folder: static/img
public_folder: /img

collections:
  - name: general
    label: "General"
    files:
    - name: controlpanel
      label: Panel de Control
      file: src/general/cp.md
      fields:
        - {label: "Sitio activo", name: "activesite", widget: "boolean", default: false}
        - label: "Numeros de telefono"
          name: "phonenumbers"
          widget: "list"
          field: {label: "Numero de telefono", name: "singlephonenumber", widget: string}
        - label: "E-mails"
          name: "emailaddresses"
          widget: "list"
          field: {label: "Direccion de email", name: "singleemailaddress", widget: string}
        - label: "Redes sociales"
          name: "social-media"
          widget: list
          field: {label: "Link de red social", name: "socialmedialink", widget: string, pattern: ['www', 'Debe ser una URL']}

  - name: pages
    label: Pages
    files:
      - file: src/pages/about-us/index.md
        label: "About Us"
        name: "about-us"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-us-page"}
          - {label: "Introduction", name: introduction, widget: text, hint: "Texto introductorio. Puede ser dejado en blanco"}
          - label: "Team Members"
            name: team-members
            widget: list
            hint: "Lista con todos los colaboradores"
            fields:
              - {label: "Name", name: "nombre", widget: string, required: true}
              - {label: "Position", name: "position", widget: string, required: true}
              - {label: "Description", name: "description", widget: text, required: true}
              - label: "Social media"
                name: "social-media"
                widget: list
                field: {label: "Social media link", name: social-media-link, widget: string, pattern: ['www', 'It needs to be an URL']}
              - {label: "Photo", name: "photo", widget: file, default: 'static/img/persona-avatar.jpg'}